name: Build Project for PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '12'
      - run: npm ci && npm run react-build
      # - uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLUELESS_GAME_6C5B6 }}'
      #     projectId: clueless-game-6c5b6
      #   env:
      #     FIREBASE_CLI_PREVIEWS: hostingchannels
